#!/usr/bin/env python3
from asnets.scripts.run_learning import main
import pdb
import sys


def debughook(etype, value, tb):
    pdb.pm()

sys.excepthook = debughook

if __name__ == '__main__':

    # pdb.set_trace()
    main()
